<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<PackageTags>Krosoft Extension Options Helper Extensions</PackageTags>
		<Description>Classes de base, extensions et helpers pour simplifier l'utilisation des options.</Description>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.7" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
	</ItemGroup>
</Project>